version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pixel/platform-pixel
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 1000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 1000
      runas: ec2-user
